#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Styling, Testing & Building your project before commiting!"

# Check Format (Prettier)
npm run check-format ||
{
    echo "Prettier check failed! Run 'npm run format', add changes & try commit again";
    false;
}

# Check Lint (ESLint)
npm run check-lint ||
{
    echo "ESLint check failed! Make the required changes listed above, add changes & try commit again";
    false;
}

# Check Types (TS Config)
npm run check-types ||
{
    echo "Failed type check! make the changes required above, add changes & try commit again";
    false;
}

# Try build project
npm run build ||
{
    echo "Your build failed! View error above";
    false;
}

echo "Success commit & ready to push!"
